### ISSUE TITLE
How to compile and how to use example

### ISSUE THREAD

**Issue by erikkjellgren** [vonDonnerstein/QuantumLab.jl#10]
Hi,

I would love to try compile and run the code (with the integrals written in Julia), but I cannot figure out how to do it. I think it might be because I am not very experienced with Julia.
But an example in the README file on how to make the program run for an input molecule with an input basis set would be great.

**Comment by vonDonnerstein** [comment]
I just noticed: I had updated the README to include a mini-tutorial in commit 7bdfe3a but never closed this issue.

To use julia integrals instead of C++ integrals (which is the default) just modify that example as follows:
julia> using QuantumLab
julia> h2o = Geometry("test/h2o.xyz")
julia> sto3g = BasisSet("sto-3g")
julia> **basis = computeBasis(sto3g,h2o)**
julia> evaluateSCF(**basis**,h2o,ZeroGuess,5)
